Document: artifex-ghostscript
Title: Debian artifex-ghostscript Manual
Author: <insert document author here>
Abstract: This manual describes what artifex-ghostscript is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/artifex-ghostscript/artifex-ghostscript.sgml.gz

Format: postscript
Files: /usr/share/doc/artifex-ghostscript/artifex-ghostscript.ps.gz

Format: text
Files: /usr/share/doc/artifex-ghostscript/artifex-ghostscript.text.gz

Format: HTML
Index: /usr/share/doc/artifex-ghostscript/html/index.html
Files: /usr/share/doc/artifex-ghostscript/html/*.html
